### ISSUE TITLE
Add to PyPI

### ISSUE THREAD

**Issue by ransford** [sampsyo/bibble#3]
I just pushed tag v0.0.1 and cleaned up `setup.py`.  @sampsyo since your name is on this thing, would you like to make sure it meets your standards and then upload it to PyPI?

**Comment by sampsyo** [comment]
Good call yo. (And good taste, using Click! I like Click!)

My career & reputation absolutely depend on the number of packages I have on PyPI, so I insist on being the one to do the release.

https://pypi.python.org/pypi/bibble
