### ISSUE TITLE
Python3 compatibility

### ISSUE THREAD

**Issue by tmoreau89** [sampsyo/bibble#7]
Having Python3 support would be really nice! Especially since Python2.7 will be deprecated by the end of the year.

**Comment by ransford** [comment]
Darn, I thought this was a pull request. I agree enough to knock it out this afternoon, though. Just for you!

**Comment by ransford** [comment]
@tmoreau89 did you run into a specific error? I am updating package metadata, but AFAICT this baby runs under Python 3 just fine.

**Comment by tmoreau89** [comment]
@ransford ah thanks! So looking into the issue, I realized that I got my bibble package via pip; which seems a little outdated: https://pypi.org/project/bibble/#history

The package on this repo actually works well! Some of the latest fixes from this repo that do support Python3 have not made it into the pip package (last updated in May 2017). You can simply diff the sources to see what has changed.

**Comment by sampsyo** [comment]
Done! https://pypi.org/project/bibble/0.0.2/

**Comment by tmoreau89** [comment]
Thanks @sampsyo !!
